### ISSUE TITLE
Exclude files/directories from st language support

### ISSUE THREAD

**Issue by rbastens** [Serhioromano/vscode-st#57]
Is it a possibility to add a setting to exclude the ST language support from different files or directories.

**Comment by Serhioromano** [comment]
This extension does not parse files that are not opened. Please explain your case. You have file extension that match this extension?

**Comment by Serhioromano** [comment]
You have an option right now in the status bar to change file language and switch what language support extension will handle it. I'll look into it that is possible to add exclude folder.

**Comment by Serhioromano** [comment]
You have an option right now in the status bar change file language and switch what language support extension will handle it. Looks like there is no way. No easy way. It is not clear to me how to do that. Because VS Code do it all itself. I only set a file extension. SO fo you only way is to switch language.
